apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-provider
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: my-provider
    spec:
      containers:
      - name: my-provider
        image: 172.20.4.27/springcloudfeign/eureka-provider:201811281252_ce6bc79
        #args:
         # - --eureka.client.serviceUrl.defaultZone=http://172.20.4.148:30201/eureka/
        ports:
        - containerPort: 30082

---
apiVersion: v1
kind: Service
metadata:
  name: my-provider
  labels:
    run: my-provider
spec:
  type: NodePort
  ports:
  - port: 30082
    targetPort: 30082
    nodePort: 30502
  selector:
    run: my-provider
