apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-consumer
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: my-consumer
    spec:
      containers:
      - name: my-consumer
        image: 172.20.4.27/springcloudfeign/eureka-consumer-feign:201811281045_6e9377d
        ports:
        - containerPort: 30083

---
apiVersion: v1
kind: Service
metadata:
  name: my-consumer
  labels:
    run: my-consumer
spec:
  type: NodePort
  ports:
  - port: 30083
    targetPort: 30083
    nodePort: 30523
  selector:
    run: my-consumer
